source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'TMDBRxMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMDBRxMVVM

  # Networking
  pod 'Moya/RxSwift'
  pod 'RxReachability'

  # RxSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

  # UI
  pod 'RAMAnimatedTabBarController'
  pod 'SnapKit'
  pod 'Kingfisher' 

  # Resource
  pod 'R.swift'
  pod "FluentIcons"

  # Debug
  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']

  target 'TMDBRxMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TMDBRxMVVMUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    # To hide deployment target warnings
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
end
