source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMDBRxMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMDBRxMVVM

  # UI
  pod 'RAMAnimatedTabBarController'
  # Resource
  pod 'R.swift'
  pod "FluentIcons"

  target 'TMDBRxMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TMDBRxMVVMUITests' do
    # Pods for testing
  end

end
